pipeline{
    agent any

    stages {
        stages('init'){
            steps{
                sh'terraform init -no-color'
            }
        }
          stages('validate'){
            steps{
                sh'terraform validate -no-color'
            }
        }
    }
}